#!/usr/bin/env bash
# Usage: vimenv completions <command> [arg1 arg2...]

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  vimenv-help --usage completions >&2
  exit 1
fi

COMMAND_PATH="$(command -v "vimenv-$COMMAND" || command -v "vimenv-sh-$COMMAND")"
if grep -i "^# provide vimenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
