#!/usr/bin/env bash
# Summary: Show the current vim version and its origin
#
# Shows the currently selected vim version and how it was
# selected. To obtain only the version string, use `vimenv
# version-name'.

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

echo "$(vimenv-version-name) (set by $(vimenv-version-origin))"
