#!/usr/bin/env bash
# Summary: Explain how the current Ruby version is set
set -e
[ -n "$VIMENV_DEBUG" ] && set -x

if [ -n "$VIMENV_VERSION" ]; then
  echo "VIMENV_VERSION environment variable"
else
  vimenv-version-file
fi
