#!/usr/bin/env bash
# Summary: List all Ruby versions that contain the given executable
# Usage: vimenv whence [--path] <command>

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

# Provide vimenv completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec vimenv shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  vimenv-versions --bare | while read version; do
    path="$(vimenv-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

VIMENV_COMMAND="$1"
if [ -z "$VIMENV_COMMAND" ]; then
  vimenv-help --usage whence >&2
  exit 1
fi

result="$(whence "$VIMENV_COMMAND")"
[ -n "$result" ] && echo "$result"
