#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: vimenv which <command>
#
# Displays the full path to the executable that vimenv will invoke when
# you run the given command.

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

# Provide vimenv completions
if [ "$1" = "--complete" ]; then
  exec vimenv shims --short
fi

expand_path() {
  if [ ! -d "$1" ]; then
    return 1
  fi

  local cwd="$(pwd)"
  cd "$1"
  pwd
  cd "$cwd"
}

remove_from_path() {
  local path_to_remove="$(expand_path "$1")"
  local result=""

  if [ -z "$path_to_remove" ]; then
    echo "${PATH}"
    return
  fi

  local paths
  IFS=: paths=($PATH)

  for path in "${paths[@]}"; do
    path="$(expand_path "$path" || true)"
    if [ -n "$path" ] && [ "$path" != "$path_to_remove" ]; then
      result="${result}${path}:"
    fi
  done

  echo "${result%:}"
}

VIMENV_VERSION="$(vimenv-version-name)"
VIMENV_COMMAND="$1"

if [ -z "$VIMENV_COMMAND" ]; then
  vimenv-help --usage which >&2
  exit 1
fi

if [ "$VIMENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${VIMENV_ROOT}/shims")"
  VIMENV_COMMAND_PATH="$(command -v "$VIMENV_COMMAND" || true)"
else
  VIMENV_COMMAND_PATH="${VIMENV_ROOT}/versions/${VIMENV_VERSION}/bin/${VIMENV_COMMAND}"
fi

for script in $(vimenv-hooks which); do
  source "$script"
done

if [ -x "$VIMENV_COMMAND_PATH" ]; then
  echo "$VIMENV_COMMAND_PATH"
else
  echo "vimenv: $VIMENV_COMMAND: command not found" >&2

  versions="$(vimenv-whence "$VIMENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Ruby versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
