#!/usr/bin/env bash
# Summary: Show the current vim version
set -e
[ -n "$VIMENV_DEBUG" ] && set -x

if [ -z "$VIMENV_VERSION" ]; then
  VIMENV_VERSION_FILE="$(vimenv-version-file)"
  VIMENV_VERSION="$(vimenv-version-file-read "$VIMENV_VERSION_FILE" || true)"
fi

if [ -z "$VIMENV_VERSION" ] || [ "$VIMENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${VIMENV_ROOT}/versions/${version}" ]
}

if version_exists "$VIMENV_VERSION"; then
  echo "$VIMENV_VERSION"
elif version_exists "${VIMENV_VERSION#vim-}"; then
  { echo "warning: ignoring extraneous \`vim-' prefix in version \`${VIMENV_VERSION}'"
    echo "         (set by $(vimenv-version-origin))"
  } >&2
  echo "${VIMENV_VERSION#vim-}"
else
  echo "vimenv: version \`$VIMENV_VERSION' is not installed" >&2
  exit 1
fi
