#!/usr/bin/env bash
set -e
export -n CDPATH

if [ "$1" = "--debug" ]; then
  export VIMENV_DEBUG=1
  shift
fi

if [ -n "$VIMENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${VIMENV_ROOT}" ]; then
  VIMENV_ROOT="${HOME}/.vimenv"
else
  VIMENV_ROOT="${VIMENV_ROOT%/}"
fi
export VIMENV_ROOT

if [ -z "${VIMENV_DIR}" ]; then
  VIMENV_DIR="$(pwd)"
else
  cd "$VIMENV_DIR" 2>/dev/null || {
    echo "vimenv: cannot change working directory to \`$VIMENV_DIR'"
    exit 1
  } >&2
  VIMENV_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export VIMENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${VIMENV_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"

hook_path="${VIMENV_HOOK_PATH}:${VIMENV_ROOT}/vimenv.d:/usr/local/etc/vimenv.d:/etc/vimenv.d:/usr/lib/vimenv/hooks"
for plugin_hook in "${VIMENV_ROOT}/plugins/"*/etc/vimenv.d; do
  hook_path="${hook_path}:${plugin_hook}"
done
export VIMENV_HOOK_PATH="$hook_path"

shopt -u nullglob


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(vimenv---version)\n$(vimenv-help)" >&2
  ;;
"-v" )
  exec vimenv---version
  ;;
* )
  command_path="$(command -v "vimenv-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "vimenv: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
