#!/usr/bin/env bash
# Summary: Configure the shell environment for vimenv
# Usage: eval "$(vimenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load vimenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and soure (vimenv init -|psub)'
      ;;
    * )
      echo 'eval "$(vimenv init -)"'
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${VIMENV_ROOT}/"{shims,versions}

if [[ ":${PATH}:" != *:"${VIMENV_ROOT}/shims":* ]]; then
  echo 'export PATH="'${VIMENV_ROOT}'/shims:${PATH}"'
fi

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/vimenv.${shell}\""
;;
fish )
  echo "set -gx PATH '${VIMENV_ROOT}/shims' \$PATH"
  echo "set -gx VIMENV_SHELL $shell"
;;
esac

if [ -z "$no_rehash" ]; then
  echo 'vimenv rehash 2>/dev/null'
fi

commands=(`vimenv-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function vimenv 
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    source (vimenv "sh-\$command" \$argv|psub)
  case '*'
    command vimenv "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function vimenv {
  typeset command
EOS
  ;;
* )
  cat <<EOS
vimenv() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
  command="\${1:-}"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(vimenv"sh-\$command" "\$@")";;
  *)
    command vimenv "\$command" "\$@";;
  esac
}
EOS
fi
