#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Ruby version
#
# Usage: vimenv shell <version>
#        vimenv shell --unset
#
# Sets a shell-specific Ruby version by setting the `VIMENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Ruby version known to vimenv.
# The special version string `system' will use your default system Ruby.
# Run `vimenv versions' for a list of available Ruby versions.

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

# Provide vimenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec vimenv-versions --bare
fi

version="$1"

if [ -z "$version" ]; then
  if [ -z "$VIMENV_VERSION" ]; then
    echo "vimenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$VIMENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  echo "unset VIMENV_VERSION"
  exit
fi

# Make sure the specified version is installed.
if vimenv-prefix "$version" >/dev/null; then
  echo "export VIMENV_VERSION=\"${version}\""
else
  echo "return 1"
  exit 1
fi
