#!/usr/bin/env bash
# Summary: Detect the file that sets the current vimenv version
set -e
[ -n "$VIMENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.vim-version" ]; then
      echo "${root}/.vim-version"
      exit
    elif [ -e "${root}/.vimenv-version" ]; then
      echo "${root}/.vimenv-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$VIMENV_DIR"
[ "$VIMENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${VIMENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${VIMENV_ROOT}/global" ]; then
  echo "${VIMENV_ROOT}/global"
elif [ -e "${VIMENV_ROOT}/default" ]; then
  echo "${VIMENV_ROOT}/default"
else
  echo "$global_version_file"
fi
