#!/usr/bin/env bash
# Summary: Display prefix for a vim version
# Usage: vimenv prefix [<version>]
#
# Displays the directory where a vim version is installed. If no
# version is given, `vimenv prefix' displays the location of the
# currently selected version.

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

# Provide vimenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec vimenv-versions --bare
fi

if [ -n "$1" ]; then
  export VIMENV_VERSION="$1"
elif [ -z "$VIMENV_VERSION" ]; then
  VIMENV_VERSION="$(vimenv-version-name)"
fi

if [ "$VIMENV_VERSION" = "system" ]; then
  if VIM_PATH="$(vimenv-which vim)"; then
    VIM_PATH="${VIM_PATH%/*}"
    VIMENV_PREFIX_PATH="${VIM_PATH%/bin}"
    echo "${VIMENV_PREFIX_PATH:-/}"
    exit
  fi
  echo "vimenv: system version not found in PTH" >&2
  exit 1
fi

VIMENV_PREFIX_PATH="${VIMENV_ROOT}/versions/${VIMENV_VERSION}"
if [ ! -d "$VIMENV_PREFIX_PATH" ]; then
  echo "vimenv: version \`${VIMENV_VERSION}' not installed" >&2
  exit 1
fi

echo "$VIMENV_PREFIX_PATH"
