#!/usr/bin/env bash
# Summary: List hook scripts for a given vimenv command
# Usage: vimenv hooks <command>

set -e
[ -n "$VIMENV_DEBUG" ] && set -x

# Provide vimenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo which
  exit
fi

VIMENV_COMMAND="$1"
if [ -z "$VIMENV_COMMAND" ]; then
  vimenv-help --usage hooks >&2
  exit 1
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

realpath() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  echo "$(pwd)/$name"
  cd "$cwd"
}

shopt -s nullglob
for path in ${VIMENV_HOOK_PATH//:/$'\n'}; do
  for script in $path/"$VIMENV_COMMAND"/*.bash; do
    echo $(realpath $script)
  done
done
shopt -u nullglob
